In [16]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
import numpy as np

rng = np.random.default_rng(2)
X = rng.random(20).reshape(-1,2)
print("\nOrijinal X\n",X)

X[:,1] = X[:,1] * 4 + 11.5
print("\n2.sütun değişti\n" , X)


X[:,0] = X[:,0] * (285-150) + 150
print("\n1.sütun değişti\n" , X)


Orijinal X
 [[0.26161213 0.29849114]
 [0.81422574 0.09191594]
 [0.60010053 0.72856053]
 [0.18790107 0.05514663]
 [0.27496937 0.65743301]
 [0.56226566 0.15006226]
 [0.43263079 0.6692973 ]
 [0.42278467 0.6331844 ]
 [0.96743595 0.68306482]
 [0.39162483 0.18725257]]

2.sütun değişti
 [[ 0.26161213 12.69396457]
 [ 0.81422574 11.86766377]
 [ 0.60010053 14.41424211]
 [ 0.18790107 11.72058651]
 [ 0.27496937 14.12973206]
 [ 0.56226566 12.10024905]
 [ 0.43263079 14.17718919]
 [ 0.42278467 14.0327376 ]
 [ 0.96743595 14.23225929]
 [ 0.39162483 12.24901028]]

1.sütun değişti
 [[185.31763812  12.69396457]
 [259.92047498  11.86766377]
 [231.01357101  14.41424211]
 [175.3666449   11.72058651]
 [187.12086467  14.12973206]
 [225.90586448  12.10024905]
 [208.40515676  14.17718919]
 [207.07593089  14.0327376 ]
 [280.60385359  14.23225929]
 [202.86935247  12.24901028]]


In [19]:

#Normalization
'''

    https://www.tensorflow.org/api_docs/python/tf/keras/layers/Normalization

'''

print("\nOrijinal X\n",X)
norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(X)  # learns mean, variance
x_change = norm_l(X)

print("\nNormalization X\n", x_change)


Orijinal X
 [[185.31763812  12.69396457]
 [259.92047498  11.86766377]
 [231.01357101  14.41424211]
 [175.3666449   11.72058651]
 [187.12086467  14.12973206]
 [225.90586448  12.10024905]
 [208.40515676  14.17718919]
 [207.07593089  14.0327376 ]
 [280.60385359  14.23225929]
 [202.86935247  12.24901028]]

Normalization X
 tf.Tensor(
[[-0.9738298  -0.4386768 ]
 [ 1.3665401  -1.2135394 ]
 [ 0.45969978  1.1745092 ]
 [-1.2860034  -1.3514602 ]
 [-0.91726077  0.90771085]
 [ 0.29946592 -0.99543244]
 [-0.24955013  0.9522133 ]
 [-0.2912493   0.8167546 ]
 [ 2.0153997   1.003856  ]
 [-0.42321396 -0.8559323 ]], shape=(10, 2), dtype=float32)
